### ISSUE TITLE
6.1.13 - Freeze during DB Prune

### ISSUE THREAD

**Issue by JayManCanada6014** [chuot/rdio-scanner#135] opened 2022-02-27 00:03 UTC
WebUI - Worked
Apps - Worked
Call Ingestion - Stop both API and Directory Watching.

All I can show you is the logs of when it started.  I had to stop and start it to get it going again.  

2022/02/26 18:09:58 newcall: system=201 talkgroup=1502 file=1502-1645916974_867637500-call_36325.m4a success
2022/02/26 18:10:00 newcall: system=102 talkgroup=35456 file=35456-1645916992_142425000-call_6605.m4a success
2022/02/26 18:10:03 newcall: system=102 talkgroup=35472 file=35472-1645916997_141525000-call_6608.m4a success
2022/02/26 18:10:05 newcall: system=102 talkgroup=35456 file=35456-1645916996_141375000-call_6607.m4a success
2022/02/26 18:10:06 newcall: system=102 talkgroup=35440 file=35440-1645917000_141735000-call_6609.m4a success
2022/02/26 18:10:10 newcall: system=102 talkgroup=35472 file=35472-1645917000_142005000-call_6610.m4a success
2022/02/26 18:10:13 newcall: system=102 talkgroup=35472 file=35472-1645917004_141525000-call_6612.m4a success
2022/02/26 18:10:20 newcall: system=102 talkgroup=35440 file=35440-1645917003_142425000-call_6611.m4a success
2022/02/26 18:10:30 newcall: system=102 talkgroup=35472 file=35472-1645917008_141735000-call_6614.m4a success
2022/02/26 18:10:30 newcall: system=102 talkgroup=35440 file=35440-1645917008_141375000-call_6615.m4a success
2022/02/26 18:10:30 newcall: system=201 talkgroup=1503 file=1503-1645916995_867537500-call_36331.m4a success
2022/02/26 18:24:28 database pruning
^C2022/02/26 19:01:04 terminated

**Comment by chuot** [comment] 2022-02-27 16:52
Were there any suspicious system logs (journalctl) around 18:10:30?

It looks like the call `system=201 talkgroup=1503 file=1503-1645916995_867537500-call_36331.m4a` froze the database even though it was logged as success. I tried finding it in the archived calls but it isn't there.

**Comment by AvalancheAddict** [comment] 2022-03-05 16:51
I was having what I believe was probably this problem (I could never tell for sure it was the pruning), but as usual I thought it was just me until seeing this.

Anyway, I just installed 6.1.15 and it looks pretty clear that it just froze during pruning.  The last log message was for the pruning and then nothing afterward.

Additional info:  I had actually started with a brand new database (I did do the basic JSON import for settings), so my database was clean.  Also, I had the pruning set to 5 days, and the freeze happened about 12 hours since the clean install, so the oldest recordings were no more than 12 hours old, so there wouldn't have been anything to prune anyway, yet it still ran something related to the pruning process & then it locked up (hopefully that tidbit proves helpful).

Thanks

**Comment by chuot** [comment] 2022-03-07 12:19
Can you post the last lines of your logs to see the time difference between the last call ingested and the database pruning. Database pruning is done in a separate thread from call ingests. What seems to hang was the thread loop for call ingestion and clients management. I've split this thread into 2 since v6.1.5 where clients management is done separately from call ingestions, in hopes of fixing this issue. Also, next time it happens, can you check if you can still browse and play archived calls from the search panel?

**Comment by AvalancheAddict** [comment] 2022-03-14 23:26
Sorry for the delayed response.  After you sent this, the location where the server resides was hit by terrible storms knocking out power for a while, and Internet longer.  I don't have any of the logs, but now that we are back and operational, I will see what I can grab if it happens again.  Thanks.

**Comment by AvalancheAddict** [comment] 2022-03-17 02:06
So I had the problem come back the other night (Dirwatch stalled after pruning started), however as I started to gather the logs and write up an explanation of my setup I realized something that I thought might be worth a look.  I have a combination of Voxcall instances and Dirwatches along with a downstream feed (both running 6.1.15), and my problem was always with the Dirwatch on the "server".  Everything else was ok.  As I was gathering the info, I started to wonder if the fact that both of my Dirwatches (the upstream one and the server one) both pointed to the same directory path and I wondered if maybe that was choking it up.  So, last night, I changed the directory name of the Dirwatch on the server and for the first time in ages have run for more than 24 hours without any Dirwatch issues.

Not sure if this makes sense or not, but it seems to me that it may not like it when you use the exact same directory path for a dirwatch on both the upstream and downstream systems.  To be specific, in my case both were pointed to c:\Proscan\Recordings on their respective hard drives.  

The weird thing is that it seems totally fine with it until the database pruning starts.  That seems to be when it dies.

I hope this helps and maybe explains a few things.

**Comment by chuot** [comment] 2022-03-17 11:37
Database pruning runs every hour and does not appear to be the cause of this issue.

Interestingly enough, having 2 instances looking at the same folder is not recommended and has never been tested. A single instance should dirwatch and downstream to other instances as needed.

Is your dirwatch set to delete after ingestion?

**Comment by AvalancheAddict** [comment] 2022-03-17 12:58
Yes the Dirwatch is set to delete upon ingestion, but to clarify the other… the two instances are not looking at the same folder.  PC1 is looking at it’s local C:/Proscan/Recordings folder and it is downstreaming to PC2 which is also running it’s own copy of Proscan and that is looking at it’s own local C:/Proscan/Recordings directory, so the two are really independent of each other, they don’t share the same directory, only the same names of directories, but on a whim, I wondered if it got confused about that somehow, so I made a Recordings2 folder on PC2 and it seems to have been ok since.

**Comment by chuot** [comment] 2022-04-25 11:50
It seems that the fix committed in v6.2.3 did the trick. Closing for now.

**Closed by chuot** 2022-04-25 11:50 UTC
Labels: investigating
