### ISSUE TITLE
screen information toggles

### ISSUE THREAD

**Issue by 8555726** [chuot/rdio-scanner#285] opened 2022-12-01 05:47 UTC
Is it possible to have the frequency field toggled in settings, so it's not shown on the screen?

**Comment by chuot** [comment] 2022-12-01 11:58
What is the reason for not displaying the frequency on which the conversation was picked up? The goal here is to reproduce a real police scanner.

**Comment by 8555726** [comment] 2022-12-01 12:00
I'm mainly using it on an APCO23 trunking system but can see your point for conventional scanning

**Comment by chuot** [comment] 2022-12-01 12:30
Well, I'm closing this as not planned. I do not wish to change the look and feel of the app. Ddisplaying the frequency is part of Rdio Scanner own identity.

**Closed by chuot** 2022-12-01 12:30 UTC
